sudo: required

language: node_js

env:
  - DOCKER_COMPOSE_VERSION=1.14.0

node_js:
  - "8"

services:
  - docker

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - export EAE_COMPUTE_VERSION=`npm version patch`
  - docker-compose --version
  - docker-compose build --build-arg version=$EAE_COMPUTE_VERSION compute
  - docker-compose up -d --remove-orphans --scale compute=3
  - docker-compose images
  - docker ps -a

script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_script:
  - docker-compose down --rmi all --remove-orphans
