swagger: '2.0'
info:
  version: 0.0.1
  title: Eae-scheduler
  license:
    name: MIT
    url: https://github.com/dsi-icl/eae-scheduler/blob/master/LICENSE
  description:  eAE Scheduler

paths:
  /status:
    get:
      description: Status report. Part of the standard API for all the eae components
      responses:
        200:
          description: Status report is active, replies the current status
          schema:
            type: object
            description: Status report
            properties:
              status:
                type: string
                description: MUST be oneof EAE_SERVICE_STATUS_XXX

  /specs:
    get:
      description: Detailed status report. Part of the standard API for eae components
      responses:
        200:
            description: desc
            schema:
                $ref: '#definitions/statusModel'
