swagger: '2.0'
info:
  version: 0.0.1
  title: Eae-compute
  license:
    name: MIT
    url: https://github.com/dsi-icl/eae-compute/blob/master/LICENSE
  description:  eAE Compute

paths:
  /status:
    get:
      description: Status report. Part of the standard API for all the eae components
      responses:
        200:
          description: Status report is active, replies the current status
          schema:
            type: object
            description: Status report
            properties:
              status:
                type: string
                description: MUST be oneof EAE_SERVICE_STATUS_XXX

  /specs:
    get:
      description: Detailed status report. Part of the standard API for eae components
      responses:
        200:
            description: desc
            schema:
                $ref: '#definitions/statusModel'

  /run/{job_id}:
    parameters:
    - name: job_id
      type: string
      in: path
      required: true
      description: Unique identifier of the job to run
    post:
        description: Starts the execution of a job
        responses:
            200:
                description: The job is being executed
                schema:
                    type: object
                    properties:
                        status:
                            type: string
                            description: Job status, MUST be oneof EAE_JOB_STATUS_XXX
            401:
                description: Missing or unknown job_id
                schema:
                    type: object
                    description: Eae ErrorStack tracking the error origin
            503:
                description: The service is already busy
                schema:
                    type: object
                    description: Eae ErrorStack

  /cancel:
    post:
      description: Cancels current task
      responses:
        200:
          description: Job has been interrupted
          schema:
            type: object
            properties:
              status:
                type: string
                description: New status of canceled job
        501:
          description: Nothing to cancel
          schema:
            type: object
            description: eAE ErrorStack with meaningful information
        500:
          description: Fail to interrupt job
          schema:
            type: object
            description: eAE ErrorStack tracking the error origin

definitions:
    statusModel:
        description: Model to represent a service status
        properties:
            type:
                type: string
                description: Type of the eae service
            status:
                type: string
                description: Current status of the service. Defaults to 'eae_service_idle'
            statusLock:
                type: boolean
                description: Lock used to prevent the service status update
            lastUpdate:
                type: string
                format: dateTime
                description: Timestamp of the last update of this model
            port:
                type: integer
                description: TCP Port the service is listening on
            ip:
                type: string
                description: IPv4 address of the machine
            hostname:
                type: string
                description: Domain name associated with this machine
            system:
                type: object
                description: Hardware speciciafations
                properties:
                    arch:
                        type: string
                        description: System architecture label
                    type:
                        type: string
                        description: System type label
                    platform:
                        type: string
                        description: Operating system name
                    version:
                        type: string
                        description: Operation system version number
            cpu:
                type: object
                description: Information about the cpu
                properties:
                    cores:
                        type: array
                        items:
                            type: object
                            description: A single core properties list
                    loadavg:
                        type: array
                        description: The load average for the last 1, 5 and 15 minutes
                        items:
                            type: number
            memory:
                type: object
                description: Information about the memory
                properties:
                    total:
                        type: string
                        description: Total memory on the system. Unit is provided in the value
                    free:
                        type: string
                        description: Available memory on the system. Unit is provided in the value

    jobModel:
        type: object
        properties:
            id:
                type: string
                description: Unique identifier
            type:
                type: string
                description: Job type definition, MUST be oneof EAE_JOB_TYPE_XXX
            status:
                type: array
                description: History of jobs states
                items:
                    type: string
                    description: State of the job, MUST be one of EAE_JOB_STATUS_XXX
            startDate:
                type: string
                format: dateTime
                description: Timestamp tracking the creation of the job
            main:
                type: string
                description: Main script file to execture
            params:
                type: array
                description: Command line parameters for the script
                items:
                    type: string
                    description: One parameter, can contain spaces
            input:
                type: array
                description: List of file inputs for this job, including main script
                items:
                    type: string
                    description: Name of one input file
            endDate:
                type: string
                format: dateTime
                description: Timestamp of when the job stops
            exitCode:
                type: integer
                description: Exit code of the job processus
            stdout:
                type: string
                description: Standard ouput TTY of the job processus
            stderr:
                type: string
                description: Standard error TTY of the job processus
            output:
                type: array
                description: List of files created in the local 'output' folder by the job process
                items:
                    type: string
                    description: Name of the file
            message:
                type: string
                description: Informative message on the last update operation
